import { LanguageCode, Service, TranslationDictionary, SiteConfig, BlogPost } from './types';

export const SUPPORTED_LANGUAGES: { code: LanguageCode; name: string; flag: string }[] = [
  { code: 'me', name: 'Montenegrin', flag: '🇲🇪' },
  { code: 'sr', name: 'Serbian', flag: '🇷🇸' },
  { code: 'hr', name: 'Croatian', flag: '🇭🇷' },
  { code: 'en', name: 'English', flag: '🇬🇧' },
  { code: 'ru', name: 'Russian', flag: '🇷🇺' },
  { code: 'de', name: 'German', flag: '🇩🇪' },
  { code: 'uk', name: 'Ukrainian', flag: '🇺🇦' },
  { code: 'tr', name: 'Turkish', flag: '🇹🇷' },
  { code: 'es', name: 'Spanish', flag: '🇪🇸' },
  { code: 'zh-HK', name: 'Cantonese', flag: '🇭🇰' },
  { code: 'zh-CN', name: 'Mandarin', flag: '🇨🇳' },
  { code: 'ja', name: 'Japanese', flag: '🇯🇵' },
  { code: 'hi', name: 'Hindi', flag: '🇮🇳' },
];

export const DEFAULT_CONFIG: SiteConfig = {
  primaryColor: '#107490',
  accentColor: '#0891b2',
  contactEmail: 'admin@montenegropropertyservices.me',
  phoneNumber: '+382 69 000 000',
  address: 'Tivat, Montenegro',
  aboutTitle: {
    'me': 'O Nama',
    'sr': 'O Nama',
    'hr': 'O Nama',
    'en': 'About Us',
    'ru': 'О Нас',
    'de': 'Über Uns',
    'uk': 'Про Нас',
    'tr': 'Hakkımızda',
    'es': 'Sobre Nosotros',
    'zh-HK': '關於我哋',
    'zh-CN': '关于我们',
    'ja': '会社概要',
    'hi': 'हमारे बारे में'
  },
  aboutSubtitle: {
    'me': 'Posvećeni izvrsnosti u održavanju nekretnina.',
    'sr': 'Posvećeni izvrsnosti u održavanju nekretnina.',
    'hr': 'Posvećeni izvrsnosti u održavanju nekretnina.',
    'en': 'Dedicated to excellence in property maintenance.',
    'ru': 'Стремление к совершенству в обслуживании недвижимости.',
    'de': 'Dem Ziel verpflichtet, exzellente Immobilienpflege zu bieten.',
    'uk': 'Віддані досконалості в обслуговуванні нерухомості.',
    'tr': 'Mülk bakımında mükemmelliğe adanmıştır.',
    'es': 'Dedicados a la excelencia en el mantenimiento de propiedades.',
    'zh-HK': '致力於卓越嘅物業維護。',
    'zh-CN': '致力于卓越的物业维护。',
    'ja': '卓越した不動産管理への献身。',
    'hi': 'संपत्ति के रखरखाव में उत्कृष्टता के लिए समर्पित।'
  },
  aboutContent: {
    'me': 'Montenegro Property Services je osnovan sa jednostavnom misijom: pružiti pouzdanu, profesionalnu i transparentnu brigu o nekretninama za međunarodne vlasnike. Razumijemo jedinstvene izazove održavanja doma u mediteranskoj klimi dok živite u inostranstvu.',
    'sr': 'Montenegro Property Services je osnovan sa jednostavnom misijom: pružiti pouzdanu, profesionalnu i transparentnu brigu o nekretninama za međunarodne vlasnike. Razumemo jedinstvene izazove održavanja doma u mediteranskoj klimi dok živite u inostranstvu.',
    'hr': 'Montenegro Property Services osnovan je s jednostavnom misijom: pružiti pouzdanu, profesionalnu i transparentnu brigu o nekretninama za međunarodne vlasnike. Razumijemo jedinstvene izazove održavanja doma u mediteranskoj klimi dok živite u inozemstvu.',
    'en': 'Montenegro Property Services was founded with a simple mission: to provide reliable, professional, and transparent property care for international owners. We understand the unique challenges of maintaining a home in a Mediterranean climate while living abroad.',
    'ru': 'Montenegro Property Services была основана с простой миссией: предоставлять надежный, профессиональный и прозрачный уход за недвижимостью для иностранных владельцев. Мы понимаем уникальные проблемы содержания дома в средиземноморском климате, проживая за границей.',
    'de': 'Montenegro Property Services wurde mit einer einfachen Mission gegründet: zuverlässige, professionelle und transparente Immobilienpflege für internationale Eigentümer anzubieten. Wir verstehen die einzigartigen Herausforderungen, ein Haus in einem mediterranen Klima zu unterhalten, während man im Ausland lebt.',
    'uk': 'Компанія Montenegro Property Services була заснована з простою місією: надавати надійний, професійний та прозорий догляд за нерухомістю для іноземних власників. Ми розуміємо унікальні виклики утримання будинку в середземноморському кліматі, проживаючи за кордоном.',
    'tr': 'Montenegro Property Services, uluslararası mülk sahipleri için güvenilir, profesyonel ve şeffaf mülk bakımı sağlama misyonuyla kuruldu. Yurt dışında yaşarken Akdeniz ikliminde bir evi korumanın benzersiz zorluklarını anlıyoruz.',
    'es': 'Montenegro Property Services se fundó con una misión simple: proporcionar un cuidado de propiedades fiable, profesional y transparente para propietarios internacionales. Entendemos los desafíos únicos de mantener un hogar en un clima mediterráneo mientras se vive en el extranjero.',
    'zh-HK': 'Montenegro Property Services成立嘅使命好簡單：為國際業主提供可靠、專業同透明嘅物業護理。我哋明白喺國外居住，同時要喺地中海氣候下維護一個家所面臨嘅獨特挑戰。',
    'zh-CN': 'Montenegro Property Services的创立使命很简单：为国际业主提供可靠、专业和透明的物业护理。我们了解在国外居住，同时要在地中海气候下维护一个家所面临的独特挑战。',
    'ja': 'モンテネグロ・プロパティ・サービスは、海外のオーナー様のために、信頼性が高く、専門的で透明性のある不動産ケアを提供することを使命として設立されました。海外に住みながら地中海性気候の家を維持するというユニークな課題を私たちは理解しています。',
    'hi': 'मोंटेनेग्रो प्रॉपर्टी सर्विसेज की स्थापना एक सरल मिशन के साथ की गई थी: अंतरराष्ट्रीय मालिकों के लिए विश्वसनीय, पेशेवर और पारदर्शी संपत्ति देखभाल प्रदान करना। हम विदेश में रहते हुए भूमध्यसाγीय जलवायु में एक घर के रखरखाव की अनूठी चुनौतियों को समझते हैं।'
  },
};

export const INITIAL_SERVICES: Service[] = [
  {
    id: '4',
    category: 'maintenance',
    icon: 'Home',
    title: {
      'me': 'Održavanje Domaćinstva', 'sr': 'Održavanje Domaćinstva', 'hr': 'Održavanje Kućanstva', 'en': 'Housekeeping', 'ru': 'Уборка и ведение хозяйства', 'de': 'Haushaltsführung', 'uk': 'Прибирання та догляд за домом', 'tr': 'Ev Hizmetleri', 'es': 'Servicio Doméstico', 'zh-HK': '家政服務', 'zh-CN': '家政服务', 'ja': 'ハウスキーピング', 'hi': 'गृह व्यवस्था'
    },
    description: {
      'me': 'Profesionalno čišćenje, usluge posteljine i priprema za dolazak.', 'sr': 'Profesionalno čišćenje, usluge posteljine i priprema za dolazak.', 'hr': 'Profesionalno čišćenje, usluge posteljine i priprema za dolazak.', 'en': 'Professional cleaning, linen service, and arrival prep.', 'ru': 'Профессиональная уборка, смена белья и подготовка к приезду.', 'de': 'Professionelle Reinigung, Wäscheservice und Vorbereitung der Ankunft.', 'uk': 'Професійне прибирання, послуги з білизною та підготовка до приїзду.', 'tr': 'Profesyonel temizlik, nevresim hizmeti ve varış hazırlığı.', 'es': 'Limpieza profesional, servicio de sábanas y preparación para la llegada.', 'zh-HK': '專業清潔、布草服務及入住準備。', 'zh-CN': '专业清洁、布草服务及入住准备。', 'ja': 'プロの清掃、リネンサービス、到着準備。', 'hi': 'पेशेवर सफाई, लिनन सेवा, और आगमन की तैयारी।'
    },
    details: {
      'me': ['Potpuno profesionalno čišćenje', 'Priprema prije dolaska', 'Usluga posteljine i pranja veša', 'Dubinsko sezonsko čišćenje', 'Usluga nakon oluje ili ponovnog otvaranja zimi'],
      'sr': ['Potpuno profesionalno čišćenje', 'Priprema pre dolaska', 'Usluga posteljine i pranja veša', 'Dubinsko sezonsko čišćenje', 'Usluga nakon oluje ili ponovnog otvaranja zimi'],
      'hr': ['Potpuno profesionalno čišćenje', 'Priprema prije dolaska', 'Usluga posteljine i pranja rublja', 'Dubinsko sezonsko čišćenje', 'Usluga nakon oluje ili ponovnog otvaranja zimi'],
      'en': ['Full professional cleaning', 'Pre-arrival preparation', 'Linen service and laundry', 'Deep seasonal cleaning', 'Post-storm or winter reopening service'],
      'ru': ['Полная профессиональная уборка', 'Подготовка к приезду', 'Смена белья и стирка', 'Генеральная сезонная уборка', 'Услуги после шторма или зимнего открытия'],
      'de': ['Vollständige professionelle Reinigung', 'Vorbereitung vor der Ankunft', 'Wäsche- und Wäschedienst', 'Saisonale Tiefenreinigung', 'Service nach Sturm oder Wiedereröffnung im Winter'],
      'uk': ['Повне професійне прибирання', 'Підготовка до приїзду', 'Послуги з білизною та прання', 'Глибоке сезонне прибирання', 'Послуги після шторму або зимового відкриття'],
      'tr': ['Tam profesyonel temizlik', 'Varış öncesi hazırlık', 'Nevresim ve çamaşır hizmeti', 'Derinlemesine mevsimlik temizlik', 'Fırtına sonrası veya kış yeniden açılış hizmeti'],
      'es': ['Limpieza profesional completa', 'Preparación antes de la llegada', 'Servicio de sábanas y lavandería', 'Limpieza profunda de temporada', 'Servicio post-tormenta o reapertura de invierno'],
      'zh-HK': ['全方位專業清潔', '入住前準備', '布草及洗衣服務', '季節性深層清潔', '風暴後或冬季重開服務'],
      'zh-CN': ['全方位专业清洁', '入住前准备', '布草及洗衣服务', '季节性深层清洁', '风暴后或冬季重开服务'],
      'ja': ['完全なプロの清掃', '到着前の準備', 'リネンとランドリーサービス', '季節的なディープクリーニング', '嵐の後や冬の再開サービス'],
      'hi': ['पूर्ण पेशेवर सफाई', 'आगमन-पूर्व तैयारी', 'लिनन और लॉन्ड्री सेवा', 'गहरी मौसमी सफाई', 'तूफान के बाद या सर्दियों में फिर से खोलने की सेवा']
    }
  },
  {
    id: '3',
    category: 'maintenance',
    icon: 'Droplets',
    title: { 'me': 'Održavanje Bazena i Spa', 'sr': 'Održavanje Bazena i Spa', 'hr': 'Njega Bazena i Spa', 'en': 'Pool & Spa Care', 'ru': 'Уход за бассейном и спа', 'de': 'Pool- & Spa-Pflege', 'uk': 'Догляд за басейном та спа', 'tr': 'Havuz & Spa Bakımı', 'es': 'Cuidado de Piscina y Spa', 'zh-HK': '泳池與水療護理', 'zh-CN': '泳池与水疗护理', 'ja': 'プール＆スパケア', 'hi': 'पूल और स्पा की देखभाल' },
    description: { 'me': 'Balansiranje hemikalija, čišćenje i servisiranje opreme.', 'sr': 'Balansiranje hemikalija, čišćenje i servisiranje opreme.', 'hr': 'Balansiranje kemikalija, čišćenje i servisiranje opreme.', 'en': 'Chemical balancing, cleaning, and equipment servicing.', 'ru': 'Балансировка химикатов, чистка и обслуживание оборудования.', 'de': 'Chemisches Gleichgewicht, Reinigung und Wartung der Ausrüstung.', 'uk': 'Балансування хімікатів, чищення та обслуговування обладнання.', 'tr': 'Kimyasal dengeleme, temizlik ve ekipman servisi.', 'es': 'Equilibrio químico, limpieza y mantenimiento de equipos.', 'zh-HK': '化學品平衡、清潔及設備維修。', 'zh-CN': '化学品平衡、清洁及设备维修。', 'ja': '化学物質のバランス調整、清掃、機器の整備。', 'hi': 'रासायनिक संतुलन, सफाई, और उपकरण सर्विसिंग।' },
    details: {
      'me': ['Testiranje i balansiranje hemikalija', 'Čišćenje i servisiranje opreme', 'Usluge otvaranja i zatvaranja'],
      'sr': ['Testiranje i balansiranje hemikalija', 'Čišćenje i servisiranje opreme', 'Usluge otvaranja i zatvaranja'],
      'hr': ['Testiranje i balansiranje kemikalija', 'Čišćenje i servisiranje opreme', 'Usluge otvaranja i zatvaranja'],
      'en': ['Chemical testing and balancing', 'Cleaning and equipment servicing', 'Opening and closing services'],
      'ru': ['Тестирование и балансировка химикатов', 'Чистка и обслуживание оборудования', 'Услуги по открытию и закрытию'],
      'de': ['Chemische Prüfung und Ausgleich', 'Reinigung und Wartung der Ausrüstung', 'Öffnungs- und Schließdienste'],
      'uk': ['Тестування та балансування хімікатів', 'Чищення та обслуговування обладнання', 'Послуги з відкриття та закриття'],
      'tr': ['Kimyasal test ve dengeleme', 'Temizlik ve ekipman servisi', 'Açılış ve kapanış hizmetleri'],
      'es': ['Análisis y equilibrio de productos químicos', 'Limpieza y mantenimiento de equipos', 'Servicios de apertura y cierre'],
      'zh-HK': ['化學品測試與平衡', '清潔及設備維修', '開放與關閉服務'],
      'zh-CN': ['化学品测试与平衡', '清洁及设备维修', '开放与关闭服务'],
      'ja': ['化学物質の試験とバランス調整', '清掃と機器の整備', '開閉サービス'],
      'hi': ['रासायनिक परीक्षण और संतुलन', 'सफाई और उपकरण सर्विसिंग', 'खोलने और बंद करने की सेवाएं']
    }
  },
  {
    id: '2',
    category: 'maintenance',
    icon: 'Hammer',
    title: { 'me': 'Tehničko Održavanje', 'sr': 'Tehničko Održavanje', 'hr': 'Tehničko Održavanje', 'en': 'Technical Maintenance', 'ru': 'Техническое обслуживание', 'de': 'Technische Wartung', 'uk': 'Технічне обслуговування', 'tr': 'Teknik Bakım', 'es': 'Mantenimiento Técnico', 'zh-HK': '技術維護', 'zh-CN': '技术维护', 'ja': '技術メンテナンス', 'hi': 'तकनीकी रखरखाव' },
    description: { 'me': 'Popravke, koordinacija sistema i održavanje zgrada.', 'sr': 'Popravke, koordinacija sistema i održavanje zgrada.', 'hr': 'Popravci, koordinacija sustava i održavanje zgrada.', 'en': 'Repairs, systems coordination, and building maintenance.', 'ru': 'Ремонт, координация систем и обслуживание зданий.', 'de': 'Reparaturen, Systemkoordination und Gebäudewartung.', 'uk': 'Ремонт, координація систем та обслуговування будівель.', 'tr': 'Onarımlar, sistem koordinasyonu ve bina bakımı.', 'es': 'Reparaciones, coordinación de sistemas y mantenimiento de edificios.', 'zh-HK': '維修、系統協調及樓宇保養。', 'zh-CN': '维修、系统协调及楼宇保养。', 'ja': '修理、システム調整、建物メンテナンス。', 'hi': 'मरम्मत, सिस्टम समन्वय, और भवन रखरखाव।' },
    details: {
      'me': ['Manje popravke i koordinacija zanatlija', 'Održavanje krova i oluka', 'Čišćenje i servis solarnih panela', 'Koordinacija vodovoda i elektrike', 'Održavanje grijanja, hlađenja i ventilacije'],
      'sr': ['Manje popravke i koordinacija zanatlija', 'Održavanje krova i oluka', 'Čišćenje i servis solarnih panela', 'Koordinacija vodovoda i elektrike', 'Održavanje grejanja, hlađenja i ventilacije'],
      'hr': ['Manji popravci i koordinacija obrtnika', 'Održavanje krova i oluka', 'Čišćenje i servis solarnih panela', 'Koordinacija vodovoda i elektrike', 'Održavanje grijanja, hlađenja i ventilacije'],
      'en': ['Minor repairs and trade coordination', 'Roof and gutter maintenance', 'Solar panel cleaning and service', 'Plumbing and electrical coordination', 'Heating, cooling and ventilation maintenance'],
      'ru': ['Мелкий ремонт и координация мастеров', 'Обслуживание крыши и водостоков', 'Чистка и обслуживание солнечных панелей', 'Координация сантехнических и электротехнических работ', 'Обслуживание систем отопления, охлаждения и вентиляции'],
      'de': ['Kleinere Reparaturen und Koordination von Handwerkern', 'Dach- und Rinnenwartung', 'Reinigung und Service von Solarmodulen', 'Koordination von Sanitär- und Elektroarbeiten', 'Wartung von Heizung, Kühlung und Lüftung'],
      'uk': ['Дрібний ремонт та координація майстрів', 'Обслуговування даху та ринв', 'Чищення та обслуговування сонячних панелей', 'Координація сантехнічних та електричних робіт', 'Обслуговування опалення, охолодження та вентиляції'],
      'tr': ['Küçük onarımlar ve esnaf koordinasyonu', 'Çatı ve oluk bakımı', 'Güneş paneli temizliği ve servisi', 'Sıhhi tesisat ve elektrik koordinasyonu', 'Isıtma, soğutma ve havalandırma bakımı'],
      'es': ['Reparaciones menores y coordinación de oficios', 'Mantenimiento de techos y canalones', 'Limpieza y servicio de paneles solares', 'Coordinación de fontanería y electricidad', 'Mantenimiento de calefacción, refrigeración y ventilación'],
      'zh-HK': ['小型維修及工匠協調', '屋頂及排水溝維護', '太陽能板清潔及服務', '水電協調', '暖通空調維護'],
      'zh-CN': ['小型维修及工匠协调', '屋顶及排水沟维护', '太阳能板清洁及服务', '水电协调', '暖通空调维护'],
      'ja': ['小規模な修理と業者調整', '屋根と雨樋のメンテナンス', 'ソーラーパネルの清掃とサービス', '配管と電気の調整', '暖房、冷房、換気のメンテナンス'],
      'hi': ['छोटी-मोटी मरम्मत और कारीगरों का समन्वय', 'छत और गटर का रखरखाव', 'सौर पैनल की सफाई और सेवा', 'नलसाजी और बिजली का समन्वय', 'हीटिंग, कूलिंग और वेंटिलेशन का रखरखाव']
    }
  },
  {
    id: '1',
    category: 'maintenance',
    icon: 'Shovel',
    title: { 'me': 'Eksterijer i Okolina', 'sr': 'Eksterijer i Okolina', 'hr': 'Eksterijer i Okoliš', 'en': 'Exterior & Grounds', 'ru': 'Экстерьер и территория', 'de': 'Außenbereich & Gelände', 'uk': 'Екстер\'єр та територія', 'tr': 'Dış Cephe ve Alanlar', 'es': 'Exterior y Terrenos', 'zh-HK': '戶外與庭院', 'zh-CN': '户外与庭院', 'ja': 'エクステリア＆敷地', 'hi': 'बाहरी और मैदान' },
    description: { 'me': 'Održavanje bašte, njega fasade i sezonska priprema.', 'sr': 'Održavanje bašte, nega fasade i sezonska priprema.', 'hr': 'Održavanje vrta, njega fasade i sezonska priprema.', 'en': 'Garden maintenance, facade care, and seasonal preparation.', 'ru': 'Уход за садом, уход за фасадом и сезонная подготовка.', 'de': 'Gartenpflege, Fassadenpflege und saisonale Vorbereitung.', 'uk': 'Догляд за садом, догляд за фасадом та сезонна підготовка.', 'tr': 'Bahçe bakımı, cephe bakımı ve mevsimsel hazırlık.', 'es': 'Mantenimiento de jardines, cuidado de fachadas y preparación estacional.', 'zh-HK': '花園維護、外牆護理及季節性準備。', 'zh-CN': '花园维护、外墙护理及季节性准备。', 'ja': '庭のメンテナンス、ファサードケア、季節の準備。', 'hi': 'बगीचे का रखरखाव, मुखौटे की देखभाल, और मौसमी तैयारी।' },
    details: {
      'me': ['Održavanje bašte i pejzaža', 'Sezonsko sađenje i obnova', 'Pranje eksterijera i njega fasade', 'Njega terase i kamena'],
      'sr': ['Održavanje bašte i pejzaža', 'Sezonsko sađenje i obnova', 'Pranje eksterijera i nega fasade', 'Nega terase i kamena'],
      'hr': ['Održavanje vrta i krajolika', 'Sezonska sadnja i obnova', 'Pranje eksterijera i njega fasade', 'Njega terase i kamena'],
      'en': ['Garden and landscape maintenance', 'Seasonal planting and restoration', 'Exterior washing and facade care', 'Terrace and stone care'],
      'ru': ['Уход за садом и ландшафтом', 'Сезонная посадка и восстановление', 'Наружная мойка и уход за фасадом', 'Уход за террасой и камнем'],
      'de': ['Garten- und Landschaftspflege', 'Saisonale Bepanzung und Restaurierung', 'Außenreinigung und Fassadenpflege', 'Terrassen- und Steinpflege'],
      'uk': ['Догляд за садом та ландшафтом', 'Сезонна посадка та відновлення', 'Зовнішнє миття та догляд за фасадом', 'Догляд за терасою та каменем'],
      'tr': ['Bahçe ve peyzaj bakımı', 'Mevsimlik ekim ve restorasyon', 'Dış cephe yıkama ve bakımı', 'Teras ve taş bakımı'],
      'es': ['Mantenimiento de jardines y paisajes', 'Plantación y restauración estacional', 'Lavado exterior y cuidado de fachadas', 'Cuidado de terrazas y piedras'],
      'zh-HK': ['花園及景觀維護', '季節性種植與修復', '外牆清洗及護理', '露台與石材護理'],
      'zh-CN': ['花园及景观维护', '季节性种植与修复', '外墙清洗及护理', '露台与石材护理'],
      'ja': ['庭園と景観のメンテナンス', '季節の植栽と修復', '外壁洗浄とファサードケア', 'テラスと石のケア'],
      'hi': ['बगीचे और परिदृश्य का रखरखाव', 'मौसमी रोपण और बहाली', 'बाहरी धुलाई और मुखौटे की देखभाल', 'छत और पत्थर की देखभाल']
    }
  },
  {
    id: '5',
    category: 'security',
    icon: 'ShieldCheck',
    title: { 'me': 'Sigurnost i Nadzor', 'sr': 'Bezbednost i Nadzor', 'hr': 'Sigurnost i Nadzor', 'en': 'Security & Monitoring', 'ru': 'Безопасность и мониторинг', 'de': 'Sicherheit & Überwachung', 'uk': 'Безпека та моніторинг', 'tr': 'Güvenlik ve İzleme', 'es': 'Seguridad y Monitoreo', 'zh-HK': '安防與監控', 'zh-CN': '安防与监控', 'ja': 'セキュリティ＆モニタリング', 'hi': 'सुरक्षा और निगरानी' },
    description: { 'me': 'Prenos uživo, provjere i hitna reakcija.', 'sr': 'Prenos uživo, provere i hitna reakcija.', 'hr': 'Prijenos uživo, provjere i hitna reakcija.', 'en': 'Live streaming, checks, and emergency response.', 'ru': 'Прямая трансляция, проверки и экстренное реагирование.', 'de': 'Live-Streaming, Kontrollen und Notfallmaßnahmen.', 'uk': 'Пряма трансляція, перевірки та екстрене реагування.', 'tr': 'Canlı yayın, kontroller ve acil durum müdahalesi.', 'es': 'Transmisión en vivo, verificaciones y respuesta de emergencia.', 'zh-HK': '實時串流、檢查及緊急應變。', 'zh-CN': '实时串流、检查及紧急应变。', 'ja': 'ライブストリーミング、チェック、緊急対応。', 'hi': 'लाइव स्ट्रीमिंग, जांच, और आपातकालीन प्रतिक्रिया।' },
    details: {
      'me': ['Video uživo unutra i vani', 'Upozorenja na pokret i integracija pametnog alarma', 'Daljinski nadzor vrata i kapija', 'Planirane provjere imovine', 'Priprema za oluju', 'Koordinacija hitnih intervencija'],
      'sr': ['Video uživo unutra i napolju', 'Upozorenja na pokret i integracija pametnog alarma', 'Daljinski nadzor vrata i kapija', 'Planirane provere imovine', 'Priprema za oluju', 'Koordinacija hitnih intervencija'],
      'hr': ['Video uživo unutra i vani', 'Upozorenja na pokret i integracija pametnog alarma', 'Daljinski nadzor vrata i kapija', 'Planirane provjere imovine', 'Priprema za oluju', 'Koordinacija hitnih intervencija'],
      'en': ['Live video inside and outside', 'Motion alerts & Smart alarm integration', 'Remote door and gate monitoring', 'Scheduled property checks', 'Storm preparation', 'Emergency response coordination'],
      'ru': ['Прямое видео внутри и снаружи', 'Оповещения о движении и интеграция с умной сигнализацией', 'Удаленный мониторинг дверей и ворот', 'Плановые проверки объекта', 'Подготовка к шторму', 'Координация экстренного реагирования'],
      'de': ['Live-Video innen und außen', 'Bewegungsmelder & Integration von Smart-Alarmen', 'Fernüberwachung von Türen und Toren', 'Geplante Immobilienprüfungen', 'Sturmvorbereitung', 'Koordination von Notfallmaßnahmen'],
      'uk': ['Пряме відео всередині та зовні', 'Сповіщення про рух та інтеграція розумної сигналізації', 'Дистанційний моніторинг дверей та воріт', 'Заплановані перевірки об\'єкта', 'Підготовка до шторму', 'Координація екстреного реагування'],
      'tr': ['İçeride ve dışarıda canlı video', 'Hareket uyarıları ve Akıllı alarm entegrasyonu', 'Uzaktan kapı ve geçit izleme', 'Planlanmış mülk kontrolleri', 'Fırtına hazırlığı', 'Acil durum müdahale koordinasyonu'],
      'es': ['Video en vivo dentro y fuera', 'Alertas de movimiento e integración de alarma inteligente', 'Monitoreo remoto de puertas y portones', 'Verificaciones programadas de la propiedad', 'Preparación para tormentas', 'Coordinación de respuesta de emergencia'],
      'zh-HK': ['室內外實時視頻', '移動警報與智能警報集成', '遠程門禁監控', '定期物業檢查', '風暴準備', '緊急應變協調'],
      'zh-CN': ['室内外实时视频', '移动警报与智能警报集成', '远程门禁监控', '定期物业检查', '风暴准备', '紧急应变协调'],
      'ja': ['屋内外のライブビデオ', 'モーションアラートとスマートアラームの統合', 'ドアとゲートの遠隔監視', '定期的な物件チェック', '嵐への備え', '緊急対応の調整'],
      'hi': ['अंदर और बाहर लाइव वीडियो', 'गति अलर्ट और स्मार्ट अलार्म एकीकरण', 'दूरस्थ दरवाजा और गेट निगरानी', 'अनुसूचित संपत्ति जांच', 'तूफान की तैयारी', 'आपातकालीन प्रतिक्रिया समन्वय']
    }
  },
  {
    id: '6',
    category: 'assets',
    icon: 'Anchor',
    title: { 'me': 'Usluge za Plovila', 'sr': 'Usluge za Plovila', 'hr': 'Usluge za Plovila', 'en': 'Boat Services', 'ru': 'Обслуживание лодок', 'de': 'Bootsservice', 'uk': 'Обслуговування човнів', 'tr': 'Tekne Hizmetleri', 'es': 'Servicios para Barcos', 'zh-HK': '船隻服務', 'zh-CN': '船只服务', 'ja': 'ボートサービス', 'hi': 'नाव सेवाएं' },
    description: { 'me': 'Održavanje, premještanje i zimsko skladištenje.', 'sr': 'Održavanje, premeštanje i zimsko skladištenje.', 'hr': 'Održavanje, premještanje i zimsko skladištenje.', 'en': 'Maintenance, relocation, and winter storage.', 'ru': 'Обслуживание, перемещение и зимнее хранение.', 'de': 'Wartung, Umzug und Winterlagerung.', 'uk': 'Обслуговування, переміщення та зимове зберігання.', 'tr': 'Bakım, yer değiştirme ve kış depolaması.', 'es': 'Mantenimiento, reubicación y almacenamiento invernal.', 'zh-HK': '維護、遷移及冬季存放。', 'zh-CN': '维护、迁移及冬季存放。', 'ja': 'メンテナンス、移転、冬期保管。', 'hi': 'रखरखाव, स्थानांतरण, और शीतकालीन भंडारण।' },
    details: {
      'me': ['Čišćenje i inspekcija plovila', 'Koordinacija servisa motora', 'Koordinacija marine', 'Sezonska priprema', 'Premještanje plovila između marina ili zemalja', 'Organizacija zimskog skladištenja'],
      'sr': ['Čišćenje i inspekcija plovila', 'Koordinacija servisa motora', 'Koordinacija marine', 'Sezonska priprema', 'Premeštanje plovila između marina ili zemalja', 'Organizacija zimskog skladištenja'],
      'hr': ['Čišćenje i inspekcija plovila', 'Koordinacija servisa motora', 'Koordinacija marine', 'Sezonska priprema', 'Premještanje plovila između marina ili zemalja', 'Organizacija zimskog skladištenja'],
      'en': ['Boat cleaning and inspection', 'Engine service coordination', 'Marina coordination', 'Seasonal preparation', 'Boat relocation between marinas or countries', 'Winter storage organization'],
      'ru': ['Чистка и осмотр лодки', 'Координация обслуживания двигателя', 'Координация с мариной', 'Сезонная подготовка', 'Перемещение лодки между маринами или странами', 'Организация зимнего хранения'],
      'de': ['Bootsreinigung und -inspektion', 'Koordination des Motorenservice', 'Koordination der Marina', 'Saisonale Vorbereitung', 'Bootsverlagerung zwischen Marinas oder Ländern', 'Organisation der Winterlagerung'],
      'uk': ['Чищення та огляд човна', 'Координація обслуговування двигуна', 'Координація з мариною', 'Сезонна підготовка', 'Переміщення човна між маринами або країнами', 'Організація зимового зберігання'],
      'tr': ['Tekne temizliği ve denetimi', 'Motor servis koordinasyonu', 'Marina koordinasyonu', 'Mevsimsel hazırlık', 'Marinalar veya ülkeler arası tekne yer değiştirme', 'Kış depolama organizasyonu'],
      'es': ['Limpieza e inspección de barcos', 'Coordinación del servicio del motor', 'Coordinación del puerto deportivo', 'Preparación estacional', 'Reubicación de barcos entre puertos deportivos o países', 'Organización del almacenamiento invernal'],
      'zh-HK': ['船隻清潔及檢查', '引擎服務協調', '碼頭協調', '季節性準備', '船隻在碼頭或國家間的遷移', '冬季存放安排'],
      'zh-CN': ['船只清洁及检查', '引擎服务协调', '码头协调', '季节性准备', '船只在码头或国家间的迁移', '冬季存放安排'],
      'ja': ['ボートの清掃と点検', 'エンジンサービスの調整', 'マリーナの調整', '季節の準備', 'マリーナ間または国間のボートの移転', '冬期保管の手配'],
      'hi': ['नाव की सफाई और निरीक्षण', 'इंजन सेवा समन्वय', 'मरीना समन्वय', 'मौसमी तैयारी', 'मरीना या देशों के बीच नाव का स्थानांतरण', 'शीतकालीन भंडारण का संगठन']
    }
  },
  {
    id: '7',
    category: 'assets',
    icon: 'Car',
    title: { 'me': 'Usluge za Vozila', 'sr': 'Usluge za Vozila', 'hr': 'Usluge za Vozila', 'en': 'Car Services', 'ru': 'Обслуживание автомобилей', 'de': 'Autoservice', 'uk': 'Обслуговування автомобілів', 'tr': 'Araç Hizmetleri', 'es': 'Servicios para Coches', 'zh-HK': '汽車服務', 'zh-CN': '汽车服务', 'ja': 'カーサービス', 'hi': 'कार सेवाएं' },
    description: { 'me': 'Provjere paljenja, registracija i premještanje.', 'sr': 'Provere paljenja, registracija i premeštanje.', 'hr': 'Provjere paljenja, registracija i premještanje.', 'en': 'Start checks, registration, and relocation.', 'ru': 'Проверки запуска, регистрация и перемещение.', 'de': 'Startkontrollen, Registrierung und Umzug.', 'uk': 'Перевірки запуску, реєстрація та переміщення.', 'tr': 'Çalıştırma kontrolleri, tescil ve yer değiştirme.', 'es': 'Verificaciones de arranque, matriculación y reubicación.', 'zh-HK': '啟動檢查、註冊及遷移。', 'zh-CN': '启动检查、注册及迁移。', 'ja': '始動チェック、登録、移転。', 'hi': 'स्टार्ट जांच, पंजीकरण, और स्थानांतरण।' },
    details: {
      'me': ['Redovna provjera i paljenje vozila', 'Zakazivanje servisa', 'Sezonska priprema', 'Koordinacija registracije', 'Premještanje automobila iz ili u Crnu Goru'],
      'sr': ['Redovna provera i paljenje vozila', 'Zakazivanje servisa', 'Sezonsка priprema', 'Koordinacija registracije', 'Premeštanje automobila iz ili u Crnu Goru'],
      'hr': ['Redovita provjera i paljenje vozila', 'Zakazivanje servisa', 'Sezonska priprema', 'Koordinacija registracije', 'Premještanje automobila iz ili u Crnu Goru'],
      'en': ['Regular vehicle start & check', 'Service scheduling', 'Seasonal preparation', 'Registration coordination', 'Car relocation from, or to Montenegro'],
      'ru': ['Регулярный запуск и проверка автомобиля', 'Планирование обслуживания', 'Сезонная подготовка', 'Координация регистрации', 'Перемещение автомобиля из или в Черногорию'],
      'de': ['Regelmäßiger Fahrzeugstart & -check', 'Serviceplanung', 'Saisonale Vorbereitung', 'Registrierungskoordination', 'Fahrzeugverlagerung von oder nach Montenegro'],
      'uk': ['Регулярний запуск та перевірка автомобіля', 'Планування обслуговування', 'Сезонна підготовка', 'Координація реєстрації', 'Переміщення автомобіля з або до Чорногорії'],
      'tr': ['Düzenli araç çalıştırma ve kontrolü', 'Servis planlaması', 'Mevsimsel hazırlık', 'Tescil koordinasyonu', 'Karadağ\'dan veya Karadağ\'a araç taşıma'],
      'es': ['Arranque y verificación regular del vehículo', 'Programación de servicios', 'Preparación estacional', 'Coordinación de la matriculación', 'Reubicación del coche desde o hacia Montenegro'],
      'zh-HK': ['定期車輛啟動與檢查', '服務排程', '季節性準備', '註冊協調', '從黑山或到黑山的汽車遷移'],
      'zh-CN': ['定期车辆启动与检查', '服务排程', '季节性准备', '注册协调', '从黑山或到黑山的汽车迁移'],
      'ja': ['定期的な車両の始動と点検', 'サービスのスケジューリング', '季節の準備', '登録の調整', 'モンテネグロからの、またはモンテネグロへの車の移転'],
      'hi': ['नियमित वाहन स्टार्ट और जांच', 'सेवा निर्धारण', 'मौसमी तैयारी', 'पंजीकरण समन्वय', 'मोंटेनेग्रो से या मोंटेनेग्रो के लिए कार स्थानांतरण']
    }
  },
  {
    id: '8',
    category: 'lifestyle',
    icon: 'Bell',
    title: { 'me': 'Konsijerž', 'sr': 'Konsijerž', 'hr': 'Concierge', 'en': 'Concierge', 'ru': 'Консьерж', 'de': 'Concierge', 'uk': 'Консьєрж', 'tr': 'Konsiyerj', 'es': 'Conserjería', 'zh-HK': '禮賓服務', 'zh-CN': '礼宾服务', 'ja': 'コンシェルジュ', 'hi': 'द्वारपाल' },
    description: { 'me': 'Popunjavanje zaliha, nadzor računa i čuvanje ključeva.', 'sr': 'Popunjavanje zaliha, nadzor računa i čuvanje ključeva.', 'hr': 'Popunjavanje zaliha, nadzor računa i čuvanje ključeva.', 'en': 'Grocery stocking, bill supervision, and key holding.', 'ru': 'Закупка продуктов, контроль счетов и хранение ключей.', 'de': 'Lebensmittelauffüllung, Rechnungsüberwachung und Schlüsselaufbewahrung.', 'uk': 'Закупівля продуктів, контроль рахунків та зберігання ключів.', 'tr': 'Market alışverişi, fatura denetimi ve anahtar teslimi.', 'es': 'Abastecimiento de comestibles, supervisión de facturas y custodia de llaves.', 'zh-HK': '雜貨採購、賬單監督及鑰匙保管。', 'zh-CN': '杂货采购、账单监督及钥匙保管。', 'ja': '食料品の補充、請求書の監督、鍵の保管。', 'hi': 'किराने का सामान भरना, बिल पर्यवेक्षण, और चाबी रखना।' },
    details: {
      'me': ['Popunjavanje zaliha namirnica prije dolaska', 'Nadzor komunalija i računa', 'Koordinacija zanatlija', 'Čuvanje ključeva i kontrola pristupa', 'Priprema za dolazak (osvjetljenje, klima)'],
      'sr': ['Popunjavanje zaliha namirnica pre dolaska', 'Nadzor komunalija i računa', 'Koordinacija zanatlija', 'Čuvanje ključeva i kontrola pristupa', 'Priprema za dolazak (osvetljenje, klima)'],
      'hr': ['Popunjavanje zaliha namirnica prije dolaska', 'Nadzor komunalija i računa', 'Koordinacija obrtnika', 'Čuvanje ključeva i kontrola pristupa', 'Priprema za dolazak (rasvjeta, klima)'],
      'en': ['Grocery stocking before arrival', 'Utility and bill supervision', 'Trade coordination', 'Key holding and access control', 'Arrival preparation (lighting, climate)'],
      'ru': ['Закупка продуктов до приезда', 'Контроль коммунальных услуг и счетов', 'Координация мастеров', 'Хранение ключей и контроль доступа', 'Подготовка к приезду (освещение, климат)'],
      'de': ['Auffüllen von Lebensmitteln vor der Ankunft', 'Überwachung von Versorgungs- und Rechnungsleistungen', 'Koordination von Handwerkern', 'Schlüsselaufbewahrung und Zugangskontrolle', 'Vorbereitung der Ankunft (Beleuchtung, Klima)'],
      'uk': ['Закупівля продуктів до приїзду', 'Контроль комунальних послуг та рахунків', 'Координація майстрів', 'Зберігання ключів та контроль доступу', 'Підготовка до приїзду (освітлення, клімат)'],
      'tr': ['Varıştan önce market alışverişi', 'Hizmet ve fatura denetimi', 'Esnaf koordinasyonu', 'Anahtar teslimi ve erişim kontrolü', 'Varış hazırlığı (aydınlatma, iklim)'],
      'es': ['Abastecimiento de comestibles antes de la llegada', 'Supervisión de servicios y facturas', 'Coordinación de oficios', 'Custodia de llaves y control de acceso', 'Preparación para la llegada (iluminación, climatización)'],
      'zh-HK': ['到達前採購雜貨', '水電費及賬單監督', '工匠協調', '鑰匙保管及門禁控制', '到達準備（照明、空調）'],
      'zh-CN': ['到达前采购杂货', '水电费及账单监督', '工匠协调', '钥匙保管及门禁控制', '到达准备（照明、空调）'],
      'ja': ['到着前の食料品補充', '公共料金と請求書の監督', '業者調整', '鍵の保管とアクセス制御', '到着準備（照明、空調）'],
      'hi': ['आगमन से पहले किराने का सामान भरना', 'उपयोगिता और बिल पर्यवेक्षण', 'कारीगरों का समन्वय', 'चाबी रखना और पहुंच नियंत्रण', 'आगमन की तैयारी (प्रकाश, जलवायु)']
    }
  },
  {
    id: '9',
    category: 'security',
    icon: 'Zap',
    title: { 'me': 'Hitne Intervencije', 'sr': 'Hitne Intervencije', 'hr': 'Hitne Intervencije', 'en': 'Emergency Response', 'ru': 'Экстренное реагирование', 'de': 'Notfallreaktion', 'uk': 'Екстрене реагування', 'tr': 'Acil Durum Müdahalesi', 'es': 'Respuesta de Emergencia', 'zh-HK': '緊急應變', 'zh-CN': '紧急应变', 'ja': '緊急対応', 'hi': 'आपातकालीन प्रतिक्रिया' },
    description: { 'me': 'Reakcija na oluju, detekcija curenja i podrška osiguranju.', 'sr': 'Reakcija na oluju, detekcija curenja i podrška osiguranju.', 'hr': 'Reakcija na oluju, detekcija curenja i podrška osiguranju.', 'en': 'Storm response, leak detection, and insurance support.', 'ru': 'Реагирование на шторм, обнаружение утечек и страховая поддержка.', 'de': 'Sturmreaktion, Leckerkennung und Versicherungsunterstützung.', 'uk': 'Реагування на шторм, виявлення протікань та страхова підтримка.', 'tr': 'Fırtına müdahalesi, sızıntı tespiti ve sigorta desteği.', 'es': 'Respuesta a tormentas, detección de fugas y soporte de seguros.', 'zh-HK': '風暴應對、洩漏檢測及保險支援。', 'zh-CN': '风暴应对、泄漏检测及保险支援。', 'ja': '嵐への対応、漏水検知、保険サポート。', 'hi': 'तूफान प्रतिक्रिया, रिसाव का पता लगाना, और बीमा सहायता।' },
    details: {
      'me': ['Reakcija na oluje, poplave i oštećenja od vode', 'Detekcija i nadzor curenja', 'Koordinacija hitnih popravki', 'Podrška u dokumentaciji za osiguranje'],
      'sr': ['Reakcija na oluje, poplave i oštećenja od vode', 'Detekcija i nadzor curenja', 'Koordinacija hitnih popravki', 'Podrška u dokumentaciji za osiguranje'],
      'hr': ['Reakcija na oluje, poplave i oštećenja od vode', 'Detekcija i nadzor curenja', 'Koordinacija hitnih popravaka', 'Podrška u dokumentaciji za osiguranje'],
      'en': ['Storm, flood and water damage response', 'Leak detection and monitoring', 'Urgent repair coordination', 'Insurance documentation support'],
      'ru': ['Реагирование на штормы, наводнения и повреждения от воды', 'Обнаружение и мониторинг утечек', 'Координация срочного ремонта', 'Поддержка в оформлении страховой документации'],
      'de': ['Reaktion auf Sturm-, Hochwasser- und Wasserschäden', 'Leckerkennung und -überwachung', 'Koordination von dringenden Reparaturen', 'Unterstützung bei der Versicherungsdokumentation'],
      'uk': ['Реагування на шторми, повені та пошкодження від води', 'Виявлення та моніторинг протікань', 'Координація термінового ремонту', 'Підтримка в оформленні страхової документації'],
      'tr': ['Fırtına, sel ve su hasarı müdahalesi', 'Sızıntı tespiti ve izleme', 'Acil onarım koordinasyonu', 'Sigorta dokümantasyon desteği'],
      'es': ['Respuesta a tormentas, inundaciones y daños por agua', 'Detección y monitoreo de fugas', 'Coordinación de reparaciones urgentes', 'Soporte de documentación de seguros'],
      'zh-HK': ['風暴、洪水及水浸應對', '洩漏檢測與監控', '緊急維修協調', '保險文件支援'],
      'zh-CN': ['风暴、洪水及水浸应对', '泄漏检测与监控', '紧急维修协调', '保险文件支援'],
      'ja': ['嵐、洪水、水害への対応', '漏水検知と監視', '緊急修理の調整', '保険書類のサポート'],
      'hi': ['तूफान, बाढ़ और पानी की क्षति की प्रतिक्रिया', 'रिसाव का पता लगाना और निगरानी', 'तत्काल मरम्मत समन्वय', 'बीमा दस्तावेज़ीकरण सहायता']
    }
  }
];

export const INITIAL_POSTS: BlogPost[] = [
  {
    id: '1',
    date: '2023-10-15',
    image: 'https://picsum.photos/800/600?random=10',
    title: {
      'me': 'Priprema Vašeg Doma za Zimu', 'sr': 'Priprema Vašeg Doma za Zimu', 'hr': 'Priprema Vašeg Doma za Zimu', 'en': 'Preparing Your Home for Winter', 'ru': 'Подготовка вашего дома к зиме', 'de': 'Vorbereitung Ihres Hauses auf den Winter', 'uk': 'Підготовка вашого будинку до зими', 'tr': 'Evinizi Kışa Hazırlamak', 'es': 'Preparando su Hogar para el Invierno', 'zh-HK': '為你嘅家準備過冬', 'zh-CN': '为你的家准备过冬', 'ja': '冬に向けた家の準備', 'hi': 'अपने घर को सर्दियों के लिए तैयार करना'
    },
    content: {
      'me': 'Osnovni savjeti za zaštitu vaše imovine tokom vansezonskih mjeseci u Crnoj Gori. Od olujnih kapaka do kontrole vlažnosti...',
      'sr': 'Osnovni saveti za zaštitu vaše imovine tokom vansezonskih meseci u Crnoj Gori. Od olujnih kapaka do kontrole vlažnosti...',
      'hr': 'Osnovni savjeti za zaštitu vaše imovine tijekom izvansezonskih mjeseci u Crnoj Gori. Od olujnih kapaka do kontrole vlažnosti...',
      'en': 'Essential tips to protect your property during the off-season months in Montenegro. From storm shutters to humidity control...',
      'ru': 'Основные советы по защите вашей собственности в межсезонье в Черногории. От штормовых ставней до контроля влажности...',
      'de': 'Wesentliche Tipps zum Schutz Ihres Eigentums während der Nebensaisonmonate in Montenegro. Von Sturmfensterläden bis zur Feuchtigkeitskontrolle...',
      'uk': 'Основні поради щодо захисту вашої власності в міжсезоння в Чорногорії. Від штормових віконниць до контролю вологості...',
      'tr': 'Karadağ\'da sezon dışı aylarda mülkünüzü korumak için temel ipuçları. Fırtına panjurlarından nem kontrolüne kadar...',
      'es': 'Consejos esenciales para proteger su propiedad durante los meses de temporada baja en Montenegro. Desde contraventanas para tormentas hasta control de la humedad...',
      'zh-HK': '喺黑山嘅淡季月份保護你物業嘅基本貼士。由防風百葉窗到濕度控制...',
      'zh-CN': '在黑山的淡季月份保护您物业的基本贴士。从防风百叶窗到湿度控制...',
      'ja': 'モンテネグロのオフシーズン中にあなたの財産を守るための重要なヒント。暴風雨シャッターから湿度管理まで...。',
      'hi': 'मोंटेनेग्रो में ऑफ-सीजन महीनों के दौरान अपनी संपत्ति की सुरक्षा के लिए आवश्यक सुझाव। तूफान शटर से लेकर आर्द्रता नियंत्रण तक...'
    }
  }
];

export const TRANSLATIONS: TranslationDictionary = {
  // Navigation & Layout
  'nav.home': { 'me': 'Početna', 'sr': 'Početna', 'hr': 'Početna', 'en': 'Home', 'ru': 'Главная', 'de': 'Startseite', 'uk': 'Головна', 'tr': 'Ana Sayfa', 'es': 'Inicio', 'zh-HK': '主頁', 'zh-CN': '主页', 'ja': 'ホーム', 'hi': 'होम' },
  'nav.services': { 'me': 'Usluge', 'sr': 'Usluge', 'hr': 'Usluge', 'en': 'Services', 'ru': 'Услуги', 'de': 'Dienstleistungen', 'uk': 'Послуги', 'tr': 'Hizmetler', 'es': 'Servicios', 'zh-HK': '服務', 'zh-CN': '服务', 'ja': 'サービス', 'hi': 'सेवाएं' },
  'nav.contact': { 'me': 'Kontakt', 'sr': 'Kontakt', 'hr': 'Kontakt', 'en': 'Contact', 'ru': 'Контакт', 'de': 'Kontakt', 'uk': 'Контакт', 'tr': 'İletişim', 'es': 'Contacto', 'zh-HK': '聯絡', 'zh-CN': '联系', 'ja': 'お問い合わせ', 'hi': 'संपर्क' },
  'nav.about': { 'me': 'O Nama', 'sr': 'O Nama', 'hr': 'O nama', 'en': 'About', 'ru': 'О нас', 'de': 'Über uns', 'uk': 'Про нас', 'tr': 'Hakkımızda', 'es': 'Sobre', 'zh-HK': '關於', 'zh-CN': '关于', 'ja': '概要', 'hi': 'हमारे बारे में' },
  'nav.menu': { 'me': 'Meni', 'sr': 'Meni', 'hr': 'Izbornik', 'en': 'Menu', 'ru': 'Меню', 'de': 'Menü', 'uk': 'Меню', 'tr': 'Menü', 'es': 'Menú', 'zh-HK': '選單', 'zh-CN': '菜单', 'ja': 'メニュー', 'hi': 'मेन्यू' },
  'menu.title': { 'me': 'Meni', 'sr': 'Meni', 'hr': 'Izbornik', 'en': 'Menu', 'ru': 'Меню', 'de': 'Menü', 'uk': 'Меню', 'tr': 'Menü', 'es': 'Menú', 'zh-HK': '選單', 'zh-CN': '菜单', 'ja': 'メニュー', 'hi': 'मेन्यू' },
  'menu.about': { 'me': 'O Nama', 'sr': 'O Nama', 'hr': 'O nama', 'en': 'About Us', 'ru': 'О нас', 'de': 'Über uns', 'uk': 'Про нас', 'tr': 'Hakkımızda', 'es': 'Sobre Nosotros', 'zh-HK': '關於我哋', 'zh-CN': '关于我们', 'ja': '会社概要', 'hi': 'हमारे बारे में' },
  'menu.admin': { 'me': 'Admin Prijava', 'sr': 'Admin Prijava', 'hr': 'Admin Prijava', 'en': 'Admin Login', 'ru': 'Вход для администратора', 'de': 'Admin-Login', 'uk': 'Вхід для адміністратора', 'tr': 'Yönetici Girişi', 'es': 'Acceso de Administrador', 'zh-HK': '管理員登入', 'zh-CN': '管理员登录', 'ja': '管理者ログイン', 'hi': 'एडमिन लॉगिन' },
  'lang.select': { 'me': 'Izaberite Jezik', 'sr': 'Izaberite Jezik', 'hr': 'Odaberite Jezik', 'en': 'Select Language', 'ru': 'Выберите язык', 'de': 'Sprache auswählen', 'uk': 'Виберіть мову', 'tr': 'Dil Seçin', 'es': 'Seleccionar Idioma', 'zh-HK': '選擇語言', 'zh-CN': '选择语言', 'ja': '言語を選択', 'hi': 'भाषा चुनें' },

  // Hero Section
  'hero.tagline': { 'me': 'MONTENEGRO PROPERTY SERVICES', 'sr': 'MONTENEGRO PROPERTY SERVICES', 'hr': 'MONTENEGRO PROPERTY SERVICES', 'en': 'MONTENEGRO PROPERTY SERVICES', 'ru': 'MONTENEGRO PROPERTY SERVICES', 'de': 'MONTENEGRO PROPERTY SERVICES', 'uk': 'MONTENEGRO PROPERTY SERVICES', 'tr': 'MONTENEGRO PROPERTY SERVICES', 'es': 'MONTENEGRO PROPERTY SERVICES', 'zh-HK': 'MONTENEGRO PROPERTY SERVICES', 'zh-CN': 'MONTENEGRO PROPERTY SERVICES', 'ja': 'MONTENEGRO PROPERTY SERVICES', 'hi': 'MONTENEGRO PROPERTY SERVICES' },
  'hero.title': { 'me': 'Dobrodošli', 'sr': 'Dobrodošli', 'hr': 'Dobrodošli', 'en': 'Welcome', 'ru': 'Добро пожаловать', 'de': 'Willkommen', 'uk': 'Ласкаво просимо', 'tr': 'Hoş Geldiniz', 'es': 'Bienvenido', 'zh-HK': '歡迎', 'zh-CN': '欢迎', 'ja': 'ようこそ', 'hi': 'स्वागत है' },
  'hero.subtitle': { 'me': 'Zamislite da dolazite u dom koji je čist, siguran, pripremljen i spreman za vas — svaki put.', 'sr': 'Zamislite da dolazite u dom koji je čist, siguran, pripremljen i spreman za vas — svaki put.', 'hr': 'Zamislite da dolazite u dom koji je čist, siguran, pripremljen i spreman za vas — svaki put.', 'en': 'Imagine arriving to a home that is clean, safe, prepared, and ready for you — every single time.', 'ru': 'Представьте, что вы приезжаете в дом, который чист, безопасен, подготовлен и готов для вас — каждый раз.', 'de': 'Stellen Sie sich vor, Sie kommen in ein Zuhause, das sauber, sicher, vorbereitet und bereit für Sie ist – jedes einzelne Mal.', 'uk': 'Уявіть, що ви приїжджаєте в дім, який чистий, безпечний, підготовлений і готовий для вас — кожного разу.', 'tr': 'Her seferinde temiz, güvenli, hazırlanmış ve sizin için hazır bir eve geldiğinizi hayal edin.', 'es': 'Imagine llegar a un hogar que está limpio, seguro, preparado y listo para usted, cada vez.', 'zh-HK': '想像一下，每一次返到屋企，都係乾淨、安全、準備好迎接你嘅。', 'zh-CN': '想象一下，每一次回到家，都是干净、安全、准备好迎接您的。', 'ja': '清潔で安全、準備が整い、いつでもあなたを迎えられる家に到着することを想像してみてください。', 'hi': 'कल्पना कीजिए कि आप एक ऐसे घर में पहुंच रहे हैं जो साफ, सुरक्षित, तैयार और आपके लिए हर बार तैयार है।' },
  'hero.cta.quote': { 'me': 'Započnite Jednostavno', 'sr': 'Započnite Jednostavno', 'hr': 'Započnite Jednostavno', 'en': 'Simple Start', 'ru': 'Простой старт', 'de': 'Einfacher Start', 'uk': 'Простий старт', 'tr': 'Basit Başlangıç', 'es': 'Comienzo Sencillo', 'zh-HK': '簡單開始', 'zh-CN': '简单开始', 'ja': '簡単なスタート', 'hi': 'सरल शुरुआत' },
  'hero.cta.services': { 'me': 'Istražite Usluge', 'sr': 'Istražite Usluge', 'hr': 'Istražite Usluge', 'en': 'Explore Services', 'ru': 'Изучить услуги', 'de': 'Dienstleistungen erkunden', 'uk': 'Дослідити послуги', 'tr': 'Hizmetleri Keşfedin', 'es': 'Explorar Servicios', 'zh-HK': '探索服務', 'zh-CN': '探索服务', 'ja': 'サービスを見る', 'hi': 'सेवाएं एक्सप्लोर करें' },
  
  // Home Page Sections
  'home.vision.title': { 'me': 'Jedan Tim. Potpuna Briga.', 'sr': 'Jedan Tim. Potpuna Briga.', 'hr': 'Jedan Tim. Potpuna Briga.', 'en': 'One Team. Total Care.', 'ru': 'Одна команда. Полный уход.', 'de': 'Ein Team. Umfassende Betreuung.', 'uk': 'Одна команда. Повний догляд.', 'tr': 'Tek Takım. Tam Bakım.', 'es': 'Un Equipo. Cuidado Total.', 'zh-HK': '一個團隊。全面護理。', 'zh-CN': '一个团队。全面护理。', 'ja': 'ワンチーム。トータルケア。', 'hi': 'एक टीम। पूरी देखभाल।' },
  'home.vision.subtitle': { 'me': 'Modernim vlasnicima nekretnina potreban je jedan pouzdan lokalni partner — ne deset različitih uslužnih kompanija. Pružamo kompletnu brigu o imovini, održavanje, nadzor i podršku životnom stilu širom Crne Gore.', 'sr': 'Modernim vlasnicima nekretnina potreban je jedan pouzdan lokalni partner — ne deset različitih uslužnih kompanija. Pružamo kompletnu brigu o imovini, održavanje, nadzor i podršku životnom stilu širom Crne Gore.', 'hr': 'Modernim vlasnicima nekretnina potreban je jedan pouzdan lokalni partner — ne deset različitih uslužnih tvrtki. Pružamo kompletnu brigu o imovini, održavanje, nadzor i podršku životnom stilu širom Crne Gore.', 'en': 'Modern property owners need one trusted local partner — not ten different service companies. We provide complete property care, maintenance, monitoring, and lifestyle support across the entire country of Montenegro.', 'ru': 'Современным владельцам недвижимости нужен один надежный местный партнер, а не десять разных сервисных компаний. Мы предоставляем полный уход за недвижимостью, техническое обслуживание, мониторинг и поддержку образа жизни по всей Черногории.', 'de': 'Moderne Immobilienbesitzer benötigen einen vertrauenswürdigen lokalen Partner – nicht zehn verschiedene Dienstleistungsunternehmen. Wir bieten umfassende Immobilienpflege, Wartung, Überwachung und Lifestyle-Unterstützung im ganzen Land Montenegro.', 'uk': 'Сучасним власникам нерухомості потрібен один надійний місцевий партнер, а не десять різних сервісних компаній. Ми надаємо повний догляд за нерухомістю, технічне обслуговування, моніторинг та підтримку способу життя по всій Чорногорії.', 'tr': 'Modern mülk sahiplerinin on farklı hizmet şirketine değil, güvenilir tek bir yerel ortağa ihtiyacı var. Karadağ\'ın her yerinde eksiksiz mülk bakımı, bakım, izleme ve yaşam tarzı desteği sağlıyoruz.', 'es': 'Los propietarios modernos necesitan un socio local de confianza, no diez empresas de servicios diferentes. Ofrecemos cuidado completo de la propiedad, mantenimiento, monitoreo y apoyo de estilo de vida en todo el país de Montenegro.', 'zh-HK': '現代業主需要一個值得信賴嘅本地合作夥伴，而唔係十間唔同嘅服務公司。我哋喺黑山全國提供全面嘅物業護理、維護、監控同生活方式支援。', 'zh-CN': '现代业主需要一个值得信赖的本地合作伙伴，而不是十家不同的服务公司。我们在黑山全国提供全面的物业护理、维护、监控和生活方式支持。', 'ja': '現代の不動産所有者には、10の異なるサービス会社ではなく、信頼できる地元のパートナーが1社必要です。私たちはモンテネグロ全土で完全な不動産ケア、メンテナンス、監視、ライフスタイルサポートを提供しています。', 'hi': 'आधुनिक संपत्ति मालिकों को एक विश्वसनीय स्थानीय भागीदार की आवश्यकता है - दस अलग-अलग सेवा कंपनियों की नहीं। हम पूरे मोंटेनेग्रो में पूरी संपत्ति देखभाल, रखरखाव, निगरानी और जीवन शैली सहायता प्रदान करते हैं।' },
  'home.vision.tag1': { 'me': 'Bez izvođača', 'sr': 'Bez izvođača', 'hr': 'Bez izvođača', 'en': 'No contractors', 'ru': 'Без подрядчиков', 'de': 'Keine Auftragnehmer', 'uk': 'Без підрядників', 'tr': 'Müteahhit yok', 'es': 'Sin contratistas', 'zh-HK': '冇承包商', 'zh-CN': '无承包商', 'ja': '業者なし', 'hi': 'कोई ठेकेदार नहीं' },
  'home.vision.tag2': { 'me': 'Bez stresa', 'sr': 'Bez stresa', 'hr': 'Bez stresa', 'en': 'No stress', 'ru': 'Без стресса', 'de': 'Kein Stress', 'uk': 'Без стресу', 'tr': 'Stres yok', 'es': 'Sin estrés', 'zh-HK': '冇壓力', 'zh-CN': '无压力', 'ja': 'ストレスなし', 'hi': 'कोई तनाव नहीं' },
  'home.vision.tag3': { 'me': 'Bez iznenađenja', 'sr': 'Bez iznenađenja', 'hr': 'Bez iznenađenja', 'en': 'No surprises', 'ru': 'Без сюрпризов', 'de': 'Keine Überraschungen', 'uk': 'Без сюрпризів', 'tr': 'Sürpriz yok', 'es': 'Sin sorpresas', 'zh-HK': '冇驚喜', 'zh-CN': '无惊喜', 'ja': '驚きなし', 'hi': 'कोई आश्चर्य नहीं' },
  'home.services.title': { 'me': 'Osnovne Usluge', 'sr': 'Osnovne Usluge', 'hr': 'Osnovne Usluge', 'en': 'Core Services', 'ru': 'Основные услуги', 'de': 'Kerndienstleistungen', 'uk': 'Основні послуги', 'tr': 'Ana Hizmetler', 'es': 'Servicios Principales', 'zh-HK': '核心服務', 'zh-CN': '核心服务', 'ja': 'コアサービス', 'hi': 'मुख्य सेवाएं' },
  'home.services.subtitle': { 'me': 'Svaki plan prilagođavamo vlasniku, imovini i lokaciji.', 'sr': 'Svaki plan prilagođavamo vlasniku, imovini i lokaciji.', 'hr': 'Svaki plan prilagođavamo vlasniku, imovini i lokaciji.', 'en': 'We tailor every plan to the owner, the property, and the location.', 'ru': 'Мы адаптируем каждый план к владельцу, объекту и местоположению.', 'de': 'Wir passen jeden Plan an den Eigentümer, die Immobilie und den Standort an.', 'uk': 'Ми адаптуємо кожен план до власника, об\'єкта та місцезнаходження.', 'tr': 'Her planı sahibine, mülke ve konuma göre uyarlıyoruz.', 'es': 'Adaptamos cada plan al propietario, la propiedad y la ubicación.', 'zh-HK': '我哋為每位業主、每項物業同每個地點量身定制計劃。', 'zh-CN': '我们为每位业主、每项物业和每个地点量身定制计划。', 'ja': '私たちは、所有者、物件、場所に合わせてすべてのプランを調整します。', 'hi': 'हम हर योजना को मालिक, संपत्ति और स्थान के अनुरूप बनाते हैं।' },
  'home.locations.title': { 'me': 'Gdje Radimo', 'sr': 'Gde Radimo', 'hr': 'Gdje Djelujemo', 'en': 'Where We Operate', 'ru': 'Где мы работаем', 'de': 'Wo wir tätig sind', 'uk': 'Де ми працюємо', 'tr': 'Faaliyet Gösterdiğimiz Yerler', 'es': 'Donde Operamos', 'zh-HK': '我哋嘅服務範圍', 'zh-CN': '我们的服务范围', 'ja': '事業展開地域', 'hi': 'हम कहाँ काम करते हैं' },
  'home.locations.subtitle': { 'me': 'Profesionalna usluga 24/7 za vašu imovinu, tokom cijele godine.', 'sr': 'Profesionalna usluga 24/7 za vašu imovinu, tokom cele godine.', 'hr': 'Profesionalna usluga 24/7 za vašu imovinu, tijekom cijele godine.', 'en': 'Professional 24/7 service for your property, all year round.', 'ru': 'Профессиональное обслуживание вашей недвижимости 24/7, круглый год.', 'de': 'Professioneller 24/7-Service für Ihre Immobilie, das ganze Jahr über.', 'uk': 'Професійне обслуговування вашої нерухомості 24/7, цілий рік.', 'tr': 'Mülkünüz için yıl boyunca profesyonel 7/24 hizmet.', 'es': 'Servicio profesional 24/7 para su propiedad, durante todo el año.', 'zh-HK': '全年無休，為你嘅物業提供專業嘅24/7服務。', 'zh-CN': '全年无休，为您的物业提供专业的24/7服务。', 'ja': '年間を通じて、お客様の不動産にプロフェッショナルな24時間年中無休のサービスを提供します。', 'hi': 'आपकी संपत्ति के लिए साल भर पेशेवर 24/7 सेवा।' },
  'home.cta.title': { 'me': 'Započnite Jednostavno', 'sr': 'Započnite Jednostavno', 'hr': 'Započnite Jednostavno', 'en': 'Simple Start', 'ru': 'Простой старт', 'de': 'Einfacher Start', 'uk': 'Простий старт', 'tr': 'Basit Başlangıç', 'es': 'Comienzo Sencillo', 'zh-HK': '簡單開始', 'zh-CN': '简单开始', 'ja': '簡単なスタート', 'hi': 'सरल शुरुआत' },
  'home.cta.subtitle': { 'me': 'Recite nam vašu lokaciju, tip nekretnine i učestalost korišćenja. Napravićemo prilagođeni plan njege za vas.', 'sr': 'Recite nam vašu lokaciju, tip nekretnine i učestalost korišćenja. Napravićemo prilagođeni plan nege za vas.', 'hr': 'Recite nam vašu lokaciju, tip nekretnine i učestalost korištenja. Napravit ćemo prilagođeni plan njege za vas.', 'en': 'Tell us your location, property type, and usage frequency. We will build a custom care plan for you.', 'ru': 'Сообщите нам ваше местоположение, тип недвижимости и частоту использования. Мы разработаем для вас индивидуальный план ухода.', 'de': 'Teilen Sie uns Ihren Standort, den Immobilientyp und die Nutzungshäufigkeit mit. Wir erstellen für Sie einen individuellen Pflegeplan.', 'uk': 'Повідомте нам ваше місцезнаходження, тип нерухомості та частоту використання. Ми розробимо для вас індивідуальний план догляду.', 'tr': 'Bize konumunuzu, mülk türünüzü ve kullanım sıklığınızı bildirin. Sizin için özel bir bakım planı oluşturacağız.', 'es': 'Díganos su ubicación, tipo de propiedad y frecuencia de uso. Crearemos un plan de cuidado personalizado para usted.', 'zh-HK': '話我哋知你嘅位置、物業類型同使用頻率。我哋會為你制定一個度身訂造嘅護理計劃。', 'zh-CN': '告诉我们您的位置、物业类型和使用频率。我们将为您制定一个量身定制的护理计划。', 'ja': 'あなたの場所、物件の種類、利用頻度を教えてください。私たちはあなたのためにカスタムケアプランを作成します。', 'hi': 'हमें अपना स्थान, संपत्ति का प्रकार और उपयोग की आवृत्ति बताएं। हम आपके लिए एक कस्टम देखभाल योजना बनाएंगे।' },
  'home.cta.button': { 'me': 'Započnite Svoj Plan', 'sr': 'Započnite Svoj Plan', 'hr': 'Započnite Svoj Plan', 'en': 'Start Your Plan', 'ru': 'Начать ваш план', 'de': 'Starten Sie Ihren Plan', 'uk': 'Розпочніть свій план', 'tr': 'Planınızı Başlatın', 'es': 'Inicie su Plan', 'zh-HK': '開始你嘅計劃', 'zh-CN': '开始您的计划', 'ja': 'プランを開始する', 'hi': 'अपनी योजना शुरू करें' },
  'home.locations.tap_details': { 'me': 'Dodirnite za detalje', 'sr': 'Dodirnite za detalje', 'hr': 'Dodirnite za detalje', 'en': 'Tap to view details', 'ru': 'Нажмите, чтобы просмотреть детали', 'de': 'Tippen, um Details anzuzeigen', 'uk': 'Торкніться, щоб переглянути деталі', 'tr': 'Ayrıntıları görüntülemek için dokunun', 'es': 'Toca para ver los detalles', 'zh-HK': '點擊查看詳情', 'zh-CN': '点击查看详情', 'ja': 'タップして詳細を表示', 'hi': 'विवरण देखने के लिए टैप करें' },
  'home.locations.covered_locations': { 'me': 'Pokrivene Lokacije', 'sr': 'Pokrivene Lokacije', 'hr': 'Pokrivene Lokacije', 'en': 'Covered Locations', 'ru': 'Охваченные местоположения', 'de': 'Abgedeckte Standorte', 'uk': 'Охоплені локації', 'tr': 'Kapsanan Konumlar', 'es': 'Ubicaciones Cubiertas', 'zh-HK': '覆蓋地點', 'zh-CN': '覆盖地点', 'ja': '対象地域', 'hi': 'कवर किए गए स्थान' },
  'home.locations.coast_title': { 'me': 'Crnogorsko Primorje i Boka Kotorska', 'sr': 'Crnogorsko Primorje i Boka Kotorska', 'hr': 'Crnogorsko Primorje i Boka Kotorska', 'en': 'Montenegro Coast & Bay of Kotor', 'ru': 'Побережье Черногории и Которский залив', 'de': 'Küste Montenegros & Bucht von Kotor', 'uk': 'Узбережжя Чорногорії та Которська затока', 'tr': 'Karadağ Sahili ve Kotor Körfezi', 'es': 'Costa de Montenegro y Bahía de Kotor', 'zh-HK': '黑山海岸及科托爾灣', 'zh-CN': '黑山海岸及科托尔湾', 'ja': 'モンテネグロの海岸とコトル湾', 'hi': 'मोंटेनेग्रो तट और कोटर की खाड़ी' },
  'home.locations.coast_desc': { 'me': 'Od istorijskih primorskih gradova do modernih marina, razumijemo izazove održavanja primorskih nekretnina — slani vazduh, vlaga, oluje i sezonska zatvaranja.', 'sr': 'Od istorijskih primorskih gradova do modernih marina, razumemo izazove održavanja primorskih nekretnina — slani vazduh, vlaga, oluje i sezonska zatvaranja.', 'hr': 'Od povijesnih primorskih gradova do modernih marina, razumijemo izazove održavanja primorskih nekretnina — slani zrak, vlaga, oluje i sezonska zatvaranja.', 'en': 'From historic coastal towns to modern marina developments, we understand the challenges of maintaining seaside property — salt air, humidity, storms, and seasonal closures.', 'ru': 'От исторических прибрежных городов до современных марин, мы понимаем проблемы содержания приморской недвижимости — соленый воздух, влажность, штормы и сезонные закрытия.', 'de': 'Von historischen Küstenstädten bis zu modernen Jachthafenanlagen verstehen wir die Herausforderungen bei der Instandhaltung von Küsteneigentum – salzige Luft, Feuchtigkeit, Stürme und saisonale Schließungen.', 'uk': 'Від історичних прибережних міст до сучасних марин, ми розуміємо виклики утримання приморської нерухомості — солоне повітря, вологість, шторми та сезонні закриття.', 'tr': 'Tarihi sahil kasabalarından modern marina gelişmelerine kadar, deniz kenarındaki mülkleri korumanın zorluklarını anlıyoruz — tuzlu hava, nem, fırtınalar ve mevsimsel kapanışlar.', 'es': 'Desde pueblos costeros históricos hasta modernos desarrollos de marinas, entendemos los desafíos de mantener propiedades junto al mar: aire salado, humedad, tormentas y cierres estacionales.', 'zh-HK': '從歷史悠久嘅沿海城鎮到現代化嘅碼頭發展，我哋明白維護海濱物業嘅挑戰——鹽分空氣、濕度、風暴同季節性關閉。', 'zh-CN': '从历史悠久的沿海城镇到现代化的码头发展，我们了解维护海滨物业的挑战——盐分空气、湿度、风暴和季节性关闭。', 'ja': '歴史的な沿岸の町から近代的なマリーナ開発まで、海辺の不動産を維持する上での課題（塩害、湿度、嵐、季節的な閉鎖）を理解しています。', 'hi': 'ऐतिहासिक तटीय शहरों से लेकर आधुनिक मरीना विकास तक, हम समुद्र तटीय संपत्ति के रखरखाव की चुनौतियों को समझते हैं - खारी हवा, नमी, तूफान और मौसमी बंदी।' },
  'home.locations.north_title': { 'me': 'Centralni, Sjeverni i Unutrašnji Dio', 'sr': 'Centralni, Severni i Unutrašnji Deo', 'hr': 'Središnji, Sjeverni i Unutarnji Dio', 'en': 'Central, Northern & Interior', 'ru': 'Центральный, Северный и Внутренний регионы', 'de': 'Zentral, Nord & Inland', 'uk': 'Центральний, Північний та Внутрішній регіони', 'tr': 'Merkez, Kuzey ve İç Bölgeler', 'es': 'Central, Norte e Interior', 'zh-HK': '中部、北部及內陸', 'zh-CN': '中部、北部及内陆', 'ja': '中央部、北部、内陸部', 'hi': 'मध्य, उत्तरी और आंतरिक' },
  'home.locations.north_desc': { 'me': 'Bilo da se radi o gradskom stanu, planinskoj kolibi ili seoskom imanju — prilagođavamo našu uslugu klimi, infrastrukturi i sezonskim potrebama.', 'sr': 'Bilo da se radi o gradskom stanu, planinskoj kolibi ili seoskom imanju — prilagođavamo našu uslugu klimi, infrastrukturi i sezonskim potrebama.', 'hr': 'Bilo da se radi o gradskom stanu, planinskoj kolibi ili seoskom imanju — prilagođavamo našu uslugu klimi, infrastrukturi i sezonskim potrebama.', 'en': 'Whether it is a city apartment, mountain chalet, or countryside estate — we adapt our service to climate, infrastructure, and seasonal needs.', 'ru': 'Будь то городская квартира, горное шале или загородное поместье — мы адаптируем наш сервис к климату, инфраструктуре и сезонным потребностям.', 'de': 'Ob Stadtwohnung, Berghütte oder Landsitz – wir passen unseren Service an Klima, Infrastruktur und saisonale Bedürfnisse an.', 'uk': 'Будь то міська квартира, гірське шале чи заміський маєток — ми адаптуємо наш сервіс до клімату, інфраструктури та сезонних потреб.', 'tr': 'İster bir şehir dairesi, ister bir dağ evi veya bir kır mülkü olsun, hizmetimizi iklime, altyapıya ve mevsimsel ihtiyaçlara göre uyarlıyoruz.', 'es': 'Ya sea un apartamento en la ciudad, un chalet de montaña o una finca en el campo, adaptamos nuestro servicio al clima, la infraestructura y las necesidades estacionales.', 'zh-HK': '無論係城市公寓、山區木屋，定係鄉村莊園——我哋都會根據氣候、基礎設施同季節性需求調整我哋嘅服務。', 'zh-CN': '无论是城市公寓、山区木屋，还是乡村庄园——我们都会根据气候、基础设施和季节性需求调整我们的服务。', 'ja': '都会のアパート、山のシャレー、田舎の不動産であれ、私たちは気候、インフラ、季節のニーズに合わせてサービスを適応させます。', 'hi': 'चाहे वह शहर का अपार्टमेंट हो, पहाड़ी शैले हो, या ग्रामीण संपत्ति हो - हम अपनी सेवा को जलवायु, बुनियादी ढांचे और मौसमी जरूरतों के अनुकूल बनाते हैं।' },

  // Services Page
  'services.subtitle': { 'me': 'Vaša imovina ostaje zaštićena, funkcionalna i vizuelno savršena tokom cijele godine.', 'sr': 'Vaša imovina ostaje zaštićena, funkcionalna i vizuelno savršena tokom cele godine.', 'hr': 'Vaša imovina ostaje zaštićena, funkcionalna i vizualno savršena tijekom cijele godine.', 'en': 'Your property stays protected, functional and visually perfect year-round.', 'ru': 'Ваша собственность остается защищенной, функциональной и визуально идеальной круглый год.', 'de': 'Ihre Immobilie bleibt das ganze Jahr über geschützt, funktionsfähig und optisch perfekt.', 'uk': 'Ваша власність залишається захищеною, функціональною та візуально досконалою цілий рік.', 'tr': 'Mülkünüz yıl boyunca korunur, işlevsel ve görsel olarak mükemmel kalır.', 'es': 'Su propiedad se mantiene protegida, funcional y visualmente perfecta durante todo el año.', 'zh-HK': '你嘅物業全年都得到保護，功能齊全，外觀完美。', 'zh-CN': '您的物业全年都得到保护，功能齐全，外观完美。', 'ja': 'あなたの財産は一年中保護され、機能的で視覚的にも完璧な状態を保ちます。', 'hi': 'आपकी संपत्ति साल भर सुरक्षित, कार्यात्मक और देखने में उत्तम रहती है।' },
  'services.quote_btn': { 'me': 'Zatražite Ponudu', 'sr': 'Zatražite Ponudu', 'hr': 'Zatražite Ponudu', 'en': 'Request Quote', 'ru': 'Запросить расчет', 'de': 'Angebot anfordern', 'uk': 'Запросити розрахунок', 'tr': 'Teklif İste', 'es': 'Solicitar Presupuesto', 'zh-HK': '索取報價', 'zh-CN': '索取报价', 'ja': '見積もりを依頼', 'hi': 'उद्धरण का अनुरोध करें' },
  
  // Contact Page
  'contact.title': { 'me': 'Započnite', 'sr': 'Započnite', 'hr': 'Započnite', 'en': 'Get Started', 'ru': 'Начать', 'de': 'Loslegen', 'uk': 'Почати', 'tr': 'Başlayın', 'es': 'Empezar', 'zh-HK': '開始', 'zh-CN': '开始', 'ja': '始めましょう', 'hi': 'शुरू करें' },
  'contact.subtitle': { 'me': 'Recite nam malo o tome šta vam je potrebno.', 'sr': 'Recite nam malo o tome šta vam je potrebno.', 'hr': 'Recite nam malo o tome što vam je potrebno.', 'en': 'Tell us a bit about what you need.', 'ru': 'Расскажите нам немного о том, что вам нужно.', 'de': 'Erzählen Sie uns ein wenig darüber, was Sie brauchen.', 'uk': 'Розкажіть нам трохи про те, що вам потрібно.', 'tr': 'Bize neye ihtiyacınız olduğunu biraz anlatın.', 'es': 'Cuéntenos un poco sobre lo que necesita.', 'zh-HK': '話我哋知你需要啲咩。', 'zh-CN': '告诉我们您需要什么。', 'ja': '何が必要か少し教えてください。', 'hi': 'हमें अपनी ज़रूरत के बारे में थोड़ा बताएं।' },
  'form.name': { 'me': 'Ime', 'sr': 'Ime', 'hr': 'Ime', 'en': 'Name', 'ru': 'Имя', 'de': 'Name', 'uk': 'Ім\'я', 'tr': 'İsim', 'es': 'Nombre', 'zh-HK': '姓名', 'zh-CN': '姓名', 'ja': '名前', 'hi': 'नाम' },
  'form.email': { 'me': 'Email', 'sr': 'Email', 'hr': 'Email', 'en': 'Email', 'ru': 'Электронная почта', 'de': 'Email', 'uk': 'Електронна пошта', 'tr': 'E-posta', 'es': 'Correo Electrónico', 'zh-HK': '電郵', 'zh-CN': '电邮', 'ja': 'Eメール', 'hi': 'ईमेल' },
  'form.phone': { 'me': 'Telefon', 'sr': 'Telefon', 'hr': 'Telefon', 'en': 'Phone', 'ru': 'Телефон', 'de': 'Telefon', 'uk': 'Телефон', 'tr': 'Telefon', 'es': 'Teléfono', 'zh-HK': '電話', 'zh-CN': '电话', 'ja': '電話', 'hi': 'फ़ोन' },
  'form.location': { 'me': 'Lokacija', 'sr': 'Lokacija', 'hr': 'Lokacija', 'en': 'Location', 'ru': 'Местоположение', 'de': 'Standort', 'uk': 'Місцезнаходження', 'tr': 'Konum', 'es': 'Ubicación', 'zh-HK': '地點', 'zh-CN': '地点', 'ja': '場所', 'hi': 'स्थान' },
  'form.property_type': { 'me': 'Tip Nekretnine', 'sr': 'Tip Nekretnine', 'hr': 'Tip Nekretnine', 'en': 'Property Type', 'ru': 'Тип недвижимости', 'de': 'Immobilientyp', 'uk': 'Тип нерухомості', 'tr': 'Mülk Türü', 'es': 'Tipo de Propiedad', 'zh-HK': '物業類型', 'zh-CN': '物业类型', 'ja': '物件タイプ', 'hi': 'संपत्ति का प्रकार' },
  'form.help_with': { 'me': 'Kako vam možemo pomoći?', 'sr': 'Kako vam možemo pomoći?', 'hr': 'S čime vam možemo pomoći?', 'en': 'What can we help with?', 'ru': 'Чем мы можем помочь?', 'de': 'Womit können wir helfen?', 'uk': 'Чим ми можемо допомогти?', 'tr': 'Size nasıl yardımcı olabiliriz?', 'es': '¿En qué podemos ayudar?', 'zh-HK': '有咩可以幫到你？', 'zh-CN': '有什么可以帮您？', 'ja': '何をお手伝いできますか？', 'hi': 'हम किसमें मदद कर सकते हैं?' },
  'form.message': { 'me': 'Poruka', 'sr': 'Poruka', 'hr': 'Poruka', 'en': 'Message', 'ru': 'Сообщение', 'de': 'Nachricht', 'uk': 'Повідомлення', 'tr': 'Mesaj', 'es': 'Mensaje', 'zh-HK': '訊息', 'zh-CN': '信息', 'ja': 'メッセージ', 'hi': 'संदेश' },
  'form.submit': { 'me': 'Pošalji Zahtjev', 'sr': 'Pošalji Zahtev', 'hr': 'Pošalji Zahtjev', 'en': 'Send Request', 'ru': 'Отправить запрос', 'de': 'Anfrage senden', 'uk': 'Надіслати запит', 'tr': 'İstek Gönder', 'es': 'Enviar Solicitud', 'zh-HK': '發送請求', 'zh-CN': '发送请求', 'ja': 'リクエストを送信', 'hi': 'अनुरोध भेजें' },
  'form.sending': { 'me': 'Slanje...', 'sr': 'Slanje...', 'hr': 'Slanje...', 'en': 'Sending...', 'ru': 'Отправка...', 'de': 'Senden...', 'uk': 'Надсилання...', 'tr': 'Gönderiliyor...', 'es': 'Enviando...', 'zh-HK': '傳送中...', 'zh-CN': '发送中...', 'ja': '送信中...', 'hi': 'भेज रहा है...' },
  'form.success.title': { 'me': 'Zahtjev Poslat', 'sr': 'Zahtev Poslat', 'hr': 'Zahtjev Poslan', 'en': 'Request Sent', 'ru': 'Запрос отправлен', 'de': 'Anfrage gesendet', 'uk': 'Запит надіслано', 'tr': 'İstek Gönderildi', 'es': 'Solicitud Enviada', 'zh-HK': '請求已發送', 'zh-CN': '请求已发送', 'ja': 'リクエスト送信完了', 'hi': 'अनुरोध भेजा गया' },
  'form.success.message': { 'me': 'Zahtjev je uspješno poslat! Uskoro ćemo vas kontaktirati.', 'sr': 'Zahtev je uspešno poslat! Uskoro ćemo vas kontaktirati.', 'hr': 'Zahtjev je uspješno poslan! Uskoro ćemo vas kontaktirati.', 'en': 'Request sent successfully! We will contact you soon.', 'ru': 'Запрос успешно отправлен! Мы скоро с вами свяжемся.', 'de': 'Anfrage erfolgreich gesendet! Wir werden uns bald bei Ihnen melden.', 'uk': 'Запит успішно надіслано! Ми скоро з вами зв\'яжемося.', 'tr': 'İstek başarıyla gönderildi! Sizinle yakında iletişime geçeceğiz.', 'es': '¡Solicitud enviada con éxito! Nos pondremos en contacto con usted pronto.', 'zh-HK': '請求已成功發送！我哋會盡快同你聯絡。', 'zh-CN': '请求已成功发送！我们会尽快与您联系。', 'ja': 'リクエストが正常に送信されました！近いうちにご連絡いたします。', 'hi': 'अनुरोध सफलतापूर्वक भेजा गया! हम जल्द ही आपसे संपर्क करेंगे।' },
  'form.success.button': { 'me': 'Pošalji Novi Zahtjev', 'sr': 'Pošalji Novi Zahtev', 'hr': 'Pošalji Novi Zahtjev', 'en': 'Send Another Request', 'ru': 'Отправить еще один запрос', 'de': 'Weitere Anfrage senden', 'uk': 'Надіслати ще один запит', 'tr': 'Başka Bir İstek Gönder', 'es': 'Enviar Otra Solicitud', 'zh-HK': '發送另一請求', 'zh-CN': '发送另一请求', 'ja': '別のリクエストを送信', 'hi': 'एक और अनुरोध भेजें' },
  'form.property_type.apartment': { 'me': 'Apartman', 'sr': 'Apartman', 'hr': 'Apartman', 'en': 'Apartment', 'ru': 'Квартира', 'de': 'Wohnung', 'uk': 'Квартира', 'tr': 'Daire', 'es': 'Apartamento', 'zh-HK': '公寓', 'zh-CN': '公寓', 'ja': 'アパート', 'hi': 'अपार्टमेंट' },
  'form.property_type.villa': { 'me': 'Vila', 'sr': 'Vila', 'hr': 'Vila', 'en': 'Villa', 'ru': 'Вилла', 'de': 'Villa', 'uk': 'Вілла', 'tr': 'Villa', 'es': 'Villa', 'zh-HK': '別墅', 'zh-CN': '别墅', 'ja': 'ヴィラ', 'hi': 'विला' },
  'form.property_type.house': { 'me': 'Kuća', 'sr': 'Kuća', 'hr': 'Kuća', 'en': 'House', 'ru': 'Дом', 'de': 'Haus', 'uk': 'Будинок', 'tr': 'Ev', 'es': 'Casa', 'zh-HK': '房屋', 'zh-CN': '房屋', 'ja': '家', 'hi': 'घर' },
  'form.property_type.land': { 'me': 'Plac', 'sr': 'Plac', 'hr': 'Zemljište', 'en': 'Land', 'ru': 'Земельный участок', 'de': 'Grundstück', 'uk': 'Земельна ділянка', 'tr': 'Arsa', 'es': 'Terreno', 'zh-HK': '土地', 'zh-CN': '土地', 'ja': '土地', 'hi': 'भूमि' },
  'form.service.housekeeping': { 'me': 'Održavanje Domaćinstva', 'sr': 'Održavanje Domaćinstva', 'hr': 'Održavanje Kućanstva', 'en': 'Housekeeping', 'ru': 'Уборка', 'de': 'Haushaltsführung', 'uk': 'Прибирання', 'tr': 'Ev Hizmetleri', 'es': 'Limpieza', 'zh-HK': '家政', 'zh-CN': '家政', 'ja': 'ハウスキーピング', 'hi': 'गृह व्यवस्था' },
  'form.service.pool': { 'me': 'Bazen i Spa', 'sr': 'Bazen i Spa', 'hr': 'Bazen i Spa', 'en': 'Pool & Spa', 'ru': 'Бассейн и Спа', 'de': 'Pool & Spa', 'uk': 'Басейн та Спа', 'tr': 'Havuz & Spa', 'es': 'Piscina y Spa', 'zh-HK': '泳池與水療', 'zh-CN': '泳池与水疗', 'ja': 'プール＆スパ', 'hi': 'पूल और स्पा' },
  'form.service.maintenance': { 'me': 'Održavanje', 'sr': 'Održavanje', 'hr': 'Održavanje', 'en': 'Maintenance', 'ru': 'Обслуживание', 'de': 'Instandhaltung', 'uk': 'Обслуговування', 'tr': 'Bakım', 'es': 'Mantenimiento', 'zh-HK': '維護', 'zh-CN': '维护', 'ja': 'メンテナンス', 'hi': 'रखरखाव' },
  'form.service.repairs': { 'me': 'Popravke', 'sr': 'Popravke', 'hr': 'Popravci', 'en': 'Repairs', 'ru': 'Ремонт', 'de': 'Reparaturen', 'uk': 'Ремонт', 'tr': 'Onarım', 'es': 'Reparaciones', 'zh-HK': '維修', 'zh-CN': '维修', 'ja': '修理', 'hi': 'मरम्मत' },
  'form.service.concierge': { 'me': 'Konsijerž', 'sr': 'Konsijerž', 'hr': 'Concierge', 'en': 'Concierge', 'ru': 'Консьерж', 'de': 'Concierge', 'uk': 'Консьєрж', 'tr': 'Konsiyerj', 'es': 'Conserjería', 'zh-HK': '禮賓服務', 'zh-CN': '礼宾服务', 'ja': 'コンシェルジュ', 'hi': 'द्वारपाल' },
  'form.service.security': { 'me': 'Sigurnost', 'sr': 'Bezbednost', 'hr': 'Sigurnost', 'en': 'Security', 'ru': 'Безопасность', 'de': 'Sicherheit', 'uk': 'Безпека', 'tr': 'Güvenlik', 'es': 'Seguridad', 'zh-HK': '安防', 'zh-CN': '安防', 'ja': 'セキュリティ', 'hi': 'सुरक्षा' },
  'form.service.boat': { 'me': 'Plovila', 'sr': 'Plovila', 'hr': 'Plovila', 'en': 'Boat', 'ru': 'Лодка', 'de': 'Boot', 'uk': 'Човен', 'tr': 'Tekne', 'es': 'Barco', 'zh-HK': '船隻', 'zh-CN': '船只', 'ja': 'ボート', 'hi': 'नाव' },
  'form.service.car': { 'me': 'Automobil', 'sr': 'Automobil', 'hr': 'Automobil', 'en': 'Car', 'ru': 'Автомобиль', 'de': 'Auto', 'uk': 'Автомобіль', 'tr': 'Araba', 'es': 'Coche', 'zh-HK': '汽車', 'zh-CN': '汽车', 'ja': '車', 'hi': 'गाड़ी' },
  'form.service.garden': { 'me': 'Bašta', 'sr': 'Bašta', 'hr': 'Vrt', 'en': 'Garden', 'ru': 'Сад', 'de': 'Garten', 'uk': 'Сад', 'tr': 'Bahçe', 'es': 'Jardín', 'zh-HK': '花園', 'zh-CN': '花园', 'ja': '庭', 'hi': 'बगीचा' },
  'form.service.cleaning': { 'me': 'Čišćenje', 'sr': 'Čišćenje', 'hr': 'Čišćenje', 'en': 'Cleaning', 'ru': 'Чистка', 'de': 'Reinigung', 'uk': 'Чищення', 'tr': 'Temizlik', 'es': 'Limpieza', 'zh-HK': '清潔', 'zh-CN': '清洁', 'ja': '清掃', 'hi': 'सफाई' },
  'form.placeholder.location': { 'me': 'npr. Tivat', 'sr': 'npr. Tivat', 'hr': 'npr. Tivat', 'en': 'e.g. Tivat', 'ru': 'напр. Тиват', 'de': 'z.B. Tivat', 'uk': 'напр. Тіват', 'tr': 'örn. Tivat', 'es': 'p.ej. Tivat', 'zh-HK': '例如 蒂瓦特', 'zh-CN': '例如 蒂瓦特', 'ja': '例：ティヴァト', 'hi': 'उदा. तिवत' },
  'form.placeholder.phone': { 'me': '+382...', 'sr': '+382...', 'hr': '+382...', 'en': '+382...', 'ru': '+382...', 'de': '+382...', 'uk': '+382...', 'tr': '+382...', 'es': '+382...', 'zh-HK': '+382...', 'zh-CN': '+382...', 'ja': '+382...', 'hi': '+382...' },
  'form.placeholder.message': { 'me': 'Vaša poruka...', 'sr': 'Vaša poruka...', 'hr': 'Vaša poruka...', 'en': 'Your message...', 'ru': 'Ваше сообщение...', 'de': 'Ihre Nachricht...', 'uk': 'Ваше повідомлення...', 'tr': 'Mesajınız...', 'es': 'Su mensaje...', 'zh-HK': '你的訊息...', 'zh-CN': '您的信息...', 'ja': 'メッセージを入力...', 'hi': 'आपका संदेश...' },
  
  // About Page
  'about.contactInfo': { 'me': 'Kontakt Informacije', 'sr': 'Kontakt Informacije', 'hr': 'Kontakt Informacije', 'en': 'Contact Info', 'ru': 'Контактная информация', 'de': 'Kontaktinformationen', 'uk': 'Контактна інформація', 'tr': 'İletişim Bilgileri', 'es': 'Información de Contacto', 'zh-HK': '聯絡資訊', 'zh-CN': '联系信息', 'ja': '連絡先情報', 'hi': 'संपर्क जानकारी' },
};